openapi: 3.0.3
info:
  title: LDC Construction Tools API
  version: 1.0.0
  description: |
    Comprehensive API for LDC Construction Tools - a modular system for managing
    construction projects, trade teams, volunteers, and role assignments.
  contact:
    name: LDC Construction Tools Team
    email: support@ldc-construction-tools.com

servers:
  - url: http://localhost:8000/api/v1
    description: Development server
  - url: https://staging.ldc-construction-tools.com/api/v1
    description: Staging server
  - url: https://ldc-construction-tools.com/api/v1
    description: Production server

paths:
  # Health check for the entire system
  /health:
    get:
      summary: System health check
      description: Check the overall health of the LDC Construction Tools system
      tags:
        - System
      responses:
        '200':
          description: System is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  timestamp:
                    type: string
                    format: date-time
                  version:
                    type: string
                    example: "1.0.0"
                  modules:
                    type: object
                    properties:
                      role_management:
                        type: string
                        example: "healthy"
                      trade_teams:
                        type: string
                        example: "healthy"
                      volunteer_management:
                        type: string
                        example: "healthy"

  # Export functionality
  /export:
    get:
      summary: Export data
      description: Export various types of data in different formats
      tags:
        - Export
      parameters:
        - name: type
          in: query
          required: true
          description: Type of data to export
          schema:
            type: string
            enum: [volunteers, trade-teams, roles, assignments]
        - name: format
          in: query
          required: false
          description: Export format
          schema:
            type: string
            enum: [csv, xlsx, json]
            default: csv
      responses:
        '200':
          description: Export file
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
        message:
          type: string
          description: Human-readable error message
        details:
          type: object
          description: Additional error details

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []

tags:
  - name: System
    description: System-wide operations
  - name: Export
    description: Data export operations
