openapi: 3.0.3
info:
  title: Calendar Scheduling API
  description: Work assignment calendar and scheduling management
  version: 0.1.0
  contact:
    name: LDC Construction Tools
    email: support@ldc-construction-tools.org

servers:
  - url: /api/v1/calendar-scheduling
    description: Calendar Scheduling API

paths:
  /work-assignments:
    get:
      summary: Get work assignments
      parameters:
        - name: startDate
          in: query
          schema:
            type: string
            format: date-time
        - name: endDate
          in: query
          schema:
            type: string
            format: date-time
        - name: tradeTeamId
          in: query
          schema:
            type: string
        - name: status
          in: query
          schema:
            $ref: '#/components/schemas/AssignmentStatus'
      responses:
        '200':
          description: List of work assignments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WorkAssignment'
    post:
      summary: Create work assignment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWorkAssignmentRequest'
      responses:
        '201':
          description: Work assignment created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkAssignment'

  /work-assignments/{id}:
    get:
      summary: Get work assignment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Work assignment details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkAssignment'

  /calendar-events:
    get:
      summary: Get calendar events
      parameters:
        - name: startDate
          in: query
          required: true
          schema:
            type: string
            format: date-time
        - name: endDate
          in: query
          required: true
          schema:
            type: string
            format: date-time
        - name: viewType
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/CalendarViewType'
      responses:
        '200':
          description: List of calendar events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CalendarEvent'

  /resource-capacity:
    get:
      summary: Get resource capacity
      parameters:
        - name: startDate
          in: query
          required: true
          schema:
            type: string
            format: date-time
        - name: endDate
          in: query
          required: true
          schema:
            type: string
            format: date-time
        - name: resourceType
          in: query
          schema:
            $ref: '#/components/schemas/ResourceType'
      responses:
        '200':
          description: Resource capacity data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResourceCapacity'

  /conflicts/detect:
    get:
      summary: Detect scheduling conflicts
      parameters:
        - name: assignmentId
          in: query
          schema:
            type: string
      responses:
        '200':
          description: List of conflicts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SchedulingConflict'

  /templates:
    get:
      summary: Get scheduling templates
      responses:
        '200':
          description: List of templates
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SchedulingTemplate'

  /stats:
    get:
      summary: Get scheduling statistics
      responses:
        '200':
          description: Scheduling statistics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SchedulingStats'

  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service health status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  version:
                    type: string
                  timestamp:
                    type: string

components:
  schemas:
    WorkAssignment:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        tradeTeamId:
          type: string
        tradeCrewId:
          type: string
        projectId:
          type: string
        regionId:
          type: string
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        isMultiDay:
          type: boolean
        status:
          $ref: '#/components/schemas/AssignmentStatus'
        priority:
          $ref: '#/components/schemas/AssignmentPriority'
        location:
          type: string
        requiredVolunteers:
          type: array
          items:
            $ref: '#/components/schemas/VolunteerRequirement'
        assignedVolunteers:
          type: array
          items:
            $ref: '#/components/schemas/AssignedVolunteer'

    AssignmentStatus:
      type: string
      enum:
        - draft
        - scheduled
        - confirmed
        - in_progress
        - completed
        - cancelled
        - postponed

    AssignmentPriority:
      type: string
      enum:
        - low
        - medium
        - high
        - urgent

    CalendarViewType:
      type: string
      enum:
        - day
        - week
        - month
        - timeline
        - resource

    ResourceType:
      type: string
      enum:
        - trade_crew
        - volunteer
        - equipment
        - location

    VolunteerRequirement:
      type: object
      properties:
        id:
          type: string
        skillRequired:
          type: string
        experienceLevel:
          type: string
          enum: [beginner, intermediate, advanced, expert]
        quantity:
          type: integer
        isOptional:
          type: boolean

    AssignedVolunteer:
      type: object
      properties:
        id:
          type: string
        volunteerId:
          type: string
        volunteerName:
          type: string
        role:
          type: string
        skills:
          type: array
          items:
            type: string
        confirmationStatus:
          type: string
          enum: [pending, confirmed, declined, no_response]

    CalendarEvent:
      type: object
      properties:
        id:
          type: string
        assignmentId:
          type: string
        title:
          type: string
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
        allDay:
          type: boolean
        color:
          type: string
        extendedProps:
          type: object

    ResourceCapacity:
      type: object
      properties:
        resourceId:
          type: string
        resourceName:
          type: string
        resourceType:
          $ref: '#/components/schemas/ResourceType'
        date:
          type: string
          format: date-time
        totalCapacity:
          type: number
        allocatedCapacity:
          type: number
        availableCapacity:
          type: number
        utilizationPercentage:
          type: number

    SchedulingConflict:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        severity:
          type: string
          enum: [low, medium, high, critical]
        description:
          type: string
        affectedAssignments:
          type: array
          items:
            type: string
        suggestedResolution:
          type: string

    SchedulingTemplate:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        tradeTeamId:
          type: string
        duration:
          type: number
        requiredVolunteers:
          type: array
          items:
            $ref: '#/components/schemas/VolunteerRequirement'

    SchedulingStats:
      type: object
      properties:
        totalAssignments:
          type: integer
        scheduledAssignments:
          type: integer
        completedAssignments:
          type: integer
        averageUtilization:
          type: number
        conflictRate:
          type: number

    CreateWorkAssignmentRequest:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        tradeTeamId:
          type: string
        tradeCrewId:
          type: string
        projectId:
          type: string
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        location:
          type: string
        priority:
          $ref: '#/components/schemas/AssignmentPriority'
      required:
        - title
        - tradeTeamId
        - tradeCrewId
        - projectId
        - startDate
        - endDate
        - location